import { Round, Project, Donation } from '@/types';

/**
 * Mock data for development
 */

export const mockRounds: Round[] = [
  {
    id: 1,
    name: 'Q1 2025 Public Goods',
    startTime: Date.now() - 7 * 24 * 60 * 60 * 1000,
    endTime: Date.now() + 23 * 24 * 60 * 60 * 1000,
    matchingPool: '🔒 ***',
    minDonation: '0.01',
    maxDonation: '10',
    status: 'active',
    projectCount: 12,
  },
  {
    id: 2,
    name: 'Privacy Tools Round',
    startTime: Date.now() - 14 * 24 * 60 * 60 * 1000,
    endTime: Date.now() + 16 * 24 * 60 * 60 * 1000,
    matchingPool: '🔒 ***',
    minDonation: '0.005',
    maxDonation: '5',
    status: 'active',
    projectCount: 8,
  },
  {
    id: 3,
    name: 'Developer Tools 2024',
    startTime: Date.now() - 60 * 24 * 60 * 60 * 1000,
    endTime: Date.now() - 30 * 24 * 60 * 60 * 1000,
    matchingPool: '🔒 ***',
    minDonation: '0.01',
    maxDonation: '20',
    status: 'finalized',
    projectCount: 15,
  },
];

export const mockProjects: Record<number, Project[]> = {
  1: [
    {
      id: 1,
      roundId: 1,
      name: 'OpenZeppelin SDK',
      description: 'Secure smart contract development framework with battle-tested libraries and security tools.',
      metadataURI: 'ipfs://QmExample1',
      logoUrl: 'https://images.unsplash.com/photo-1633356122544-f134324a6cee?w=200',
      creator: '0x1234...5678',
      verified: true,
      donorCount: 234,
      totalDonations: '🔒 ***',
      createdAt: Date.now() - 30 * 24 * 60 * 60 * 1000,
    },
    {
      id: 2,
      roundId: 1,
      name: 'Hardhat IDE Plugin',
      description: 'Professional Solidity development environment with advanced debugging and testing features.',
      metadataURI: 'ipfs://QmExample2',
      logoUrl: 'https://images.unsplash.com/photo-1555066931-4365d14bab8c?w=200',
      creator: '0xabcd...ef01',
      verified: true,
      donorCount: 187,
      totalDonations: '🔒 ***',
      createdAt: Date.now() - 25 * 24 * 60 * 60 * 1000,
    },
    {
      id: 3,
      roundId: 1,
      name: 'Gas Optimizer',
      description: 'Automated gas optimization tool that reduces transaction costs by up to 40%.',
      metadataURI: 'ipfs://QmExample3',
      logoUrl: 'https://images.unsplash.com/photo-1639762681485-074b7f938ba0?w=200',
      creator: '0x9876...5432',
      verified: true,
      donorCount: 156,
      totalDonations: '🔒 ***',
      createdAt: Date.now() - 20 * 24 * 60 * 60 * 1000,
    },
    {
      id: 4,
      roundId: 1,
      name: 'Solidity Formatter',
      description: 'Beautiful code formatting for Solidity with customizable style rules.',
      metadataURI: 'ipfs://QmExample4',
      creator: '0x1111...2222',
      verified: false,
      donorCount: 89,
      totalDonations: '🔒 ***',
      createdAt: Date.now() - 15 * 24 * 60 * 60 * 1000,
    },
  ],
  2: [
    {
      id: 5,
      roundId: 2,
      name: 'Tor Browser Extension',
      description: 'Privacy-focused browser extension for anonymous browsing with built-in tracking protection.',
      metadataURI: 'ipfs://QmExample5',
      logoUrl: 'https://images.unsplash.com/photo-1614064641938-3bbee52942c7?w=200',
      creator: '0x3333...4444',
      verified: true,
      donorCount: 312,
      totalDonations: '🔒 ***',
      createdAt: Date.now() - 18 * 24 * 60 * 60 * 1000,
    },
    {
      id: 6,
      roundId: 2,
      name: 'Encrypted Messaging',
      description: 'End-to-end encrypted messaging platform with zero-knowledge architecture.',
      metadataURI: 'ipfs://QmExample6',
      logoUrl: 'https://images.unsplash.com/photo-1611162617474-5b21e879e113?w=200',
      creator: '0x5555...6666',
      verified: true,
      donorCount: 278,
      totalDonations: '🔒 ***',
      createdAt: Date.now() - 12 * 24 * 60 * 60 * 1000,
    },
  ],
};

export const mockDonations: Donation[] = [
  {
    id: '1',
    roundId: 1,
    projectId: 1,
    donor: '0xYourAddress',
    amount: '🔒 ***',
    timestamp: Date.now() - 24 * 60 * 60 * 1000,
    transactionHash: '0xabc123...',
  },
  {
    id: '2',
    roundId: 1,
    projectId: 2,
    donor: '0xYourAddress',
    amount: '🔒 ***',
    timestamp: Date.now() - 48 * 60 * 60 * 1000,
    transactionHash: '0xdef456...',
  },
  {
    id: '3',
    roundId: 2,
    projectId: 5,
    donor: '0xYourAddress',
    amount: '🔒 ***',
    timestamp: Date.now() - 72 * 60 * 60 * 1000,
    transactionHash: '0xghi789...',
  },
];
